# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juy4556
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: scraping-keyboard
# "service" is the name of this project. This will also be added to your AWS resource names.
service: scraping-keyboard

provider:
  name: aws
  runtime: python3.12

functions:
  hello:
    handler: handler.hello
